version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/pgData:/var/lib/postgresql/data
    networks:
      - be_network
  be:
    container_name: be
    restart: always
    depends_on:
      - postgres
    env_file: ./backend/.env
    build:
      context: ./backend
    ports:
      - "9898:9898"
    networks:
      - be_network
networks:
  be_network:
  fe_network:
